function DiffFun = MIBD_diff(n, m, u)
% The distribution of IBD sharing when the two sampled individuals are taken from different populations
% Firstly edit by Xumin, Last edit by Wei
% Input
%    - n           - population size (haploid)
%    - m           - migration rate 
%    - u           - cutoff (the length is measured in Morgan)
% Output
%    - DiffFun     - function for IBD sharing in different populations
%--------------------------------------------------------------------------
DiffFun = @(t)(1./exp(4.*n.*t.*u) + (4.*n.*t.*u)./exp(4.*n.*t.*u)).*((exp(t.*(16.*m.^2.*n.^2 + 1).^(1/2) -...
          t - 4.*m.*n.*t).*(4.*m.*n + (16.*m.^2.*n.^2 + 1).^(1/2) - 1).*(4.*m.*n - (16.*m.^2.*n.^2 + 1).^(1/2) + 1))./(8.*m.*n)...
          - (((16.*m.^2.*n.^2 + 1).^(1/2) - 4.*m.*n + 1).*(4.*m.*n + (16.*m.^2.*n.^2 + 1).^(1/2) + 1))./(8.*m.*n.*exp(t + ...
          t.*(16.*m.^2.*n.^2 + 1).^(1/2) + 4.*m.*n.*t)) + (((16.*m.^2.*n.^2 + 1).^(1/2) - 4.*m.*n + 1).*(4.*m.*n + ...
          (16.*m.^2.*n^2 + 1).^(1/2) + 1))./(8.*m.*n.*exp(t + t.*(16.*m.^2.*n.^2 + 1).^(1/2) + 4.*m.*n.*t).*(16.*m.^2.*n.^2 ...
          + 1).^(1/2)) + (exp(t.*(16.*m.^2.*n.^2 + 1).^(1/2) - t - 4.*m.*n.*t).*(4.*m.*n + (16.*m.^2.*n.^2 + 1).^(1/2) - 1).*...
          (4.*m.*n - (16.*m.^2*n.^2 + 1).^(1/2) + 1))./(8.*m.*n.*(16.*m.^2.*n.^2 + 1).^(1/2)));
% DiffFun=@(t) (8.*m.*n.*sinh(t.*(16.*m.^2.*n.^2 + 1).^(1/2)).*(4.*n.*t.*u + 1))./(exp(t + 4.*m.*n.*t + 4.*n.*t.*u).*(16.*m.^2.*n^2 + 1).^(1/2));